### ISSUE TITLE
Can't seem to whitelist items (change from getMaterial to matchMaterial)

### ISSUE THREAD

**Issue by tmoyer** [ThunderGemios10/Survival-Games#83]
I'm using:
Survival Games version 0.7.5 
Minecraft/Spigot 1.12.2
WorldEdit 6.1.9

According to your readme we're supposed to use item names rather than numerical ids, but that doesn't seem to work.

I have tried the following in config.yml to allow placing wool blocks:

```
#Here you can control block placing and breaking. 
block:
  place:
    whitelist:
    - wool
  break:
    whitelist:
    - wool
```

```
#Here you can control block placing and breaking. 
block:
  place:
    whitelist:
    - 35
  break:
    whitelist:
    - 35
```

```
#Here you can control block placing and breaking. 
block:
  place:
    whitelist:
    - wool,0
  break:
    whitelist:
    - wool,0
```

```
#Here you can control block placing and breaking. 
block:
  place:
    whitelist:
    - WOOL
  break:
    whitelist:
    - WOOL
```

```
#Here you can control block placing and breaking. 
block:
  place:
    whitelist:
    - wool_block
  break:
    whitelist:
    - wool_block
```

But none of these work.

I'm able to use wool in the chest.yml file, but not in config.yml's whitelists.
